site_name: Yves的杂货铺
site_author: Yves

repo_name: Yves的杂货铺
repo_url: https://github.com/jygzyc/notes
edit_uri: edit/main/docs/

# Configuration
theme: 
  name: material
  language: zh
  custom_dir: overrides
  favicon: assets/favicon.ico
  logo: assets/favicon.png
  palette: 
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: indigo
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: "Microsoft Yahei"
    code: "JetBrains Mono"
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/
    - navigation.footer
    - navigation.top
    - navigation.path
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/
    - search.suggest
    - search.highlight
    - search.share
    # When section index pages are enabled, documents can be directly attached to sections, which is particularly useful for providing overview pages
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.prune
    - toc.follow

# Copyright
copyright: 版权所有

# Extensions
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - def_list
  - md_in_html
  - meta
  - toc:
      permalink: true

# Additional configuration
extra_javascript:
  - js/extra.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

hooks:
  - overrides/deploy_scripts/hook_copyright.py
  - overrides/deploy_scripts/hook_meta.py

# Plugins
plugins: 
  - awesome-pages:
      strict: false
  - git-revision-date-localized:
      locale: zh
      type: iso_date
      timezone: Asia/Shanghai
      enable_creation_date: true
      exclude:
        - blog/*
        - index.md
        - message_board.md
  - search:
      lang:
        - en
        - ja
        - zh
      separator: '[\s\u200b\-]'
  - glightbox:
      auto_caption: false
      caption_position: bottom
  - minify:
      minify_html: true
  - blog:
      blog_dir: blog
      post_url_date_format: yyyy/MM
      post_url_format: "{date}/{file}"
      archive: true
      categories: true

extra:
  analytics:
    provider: google
    property: G-YJZYQKZXND

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jygzyc
      name: Ecool on GitHub
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/36193083
      name: Ecool on Bilibili
